---
title: "Introduction to data analysis in R"
format: html
---


# Introduction*

Say a few words about the project.




## Load data

```{r}
library(readr)
ESS <- read_csv("data/ESS/HR_comma_sep.csv")
```




## Calculate correlation between Murder and Rape

```{r}
res <- cor.test(ESS$satisfaction_level, ESS$last_evaluation)
res

```

the correlatin is small (r = 0.10) and highly significant (p<0.001) based on a pearson correlation test (t(14997)=12.933).

## Reporting results

```{r}
# install.packages("report")
library(report)
report(res)
```

## Plotting

```{r}


library(ggplot2)
ggplot(ESS, aes(x = last_evaluation, y=satisfaction_level, color = salary)) +
  geom_point(alpha = 0.5) +
  geom_smooth() +
  facet_wrap(~salary)


```

## Linear regressions

```{r}
m1 <- lm(satisfaction_level~last_evaluation, data=ESS)
m1
```

```{r}
anova(m1)
```

## Using the report package

```{r echo=TRUE}
report(m1)
```

## Plotting

```{r echo=TRUE}

plot(ESS$last_evaluation, ESS$satisfaction_level)
abline(m1, col = "red")

```

```{r}
# plot(m1)
```

